# -*- coding: utf-8 -*-
"""Bilingual (English/Hindi) label strings for the compliance checker."""

FIELD_LABELS_HI = {
    "manufacturer_details": "निर्माता/पैकर/आयातक का नाम एवं पता",
    "common_name": "वस्तु का सामान्य या जेनेरिक नाम",
    "net_quantity": "मानक इकाइयों में शुद्ध मात्रा (वज़न, आयतन अथवा संख्या)",
    "mrp": "अधिकतम खुदरा मूल्य (सभी करों सहित)",
    "mfg_date": "निर्माण/पैकिंग/आयात का माह एवं वर्ष",
    "consumer_care": "उपभोक्ता सेवा विवरण (नाम, पता, टेलीफोन/ईमेल)",
    "font_legibility": "घोषणाओं का फ़ॉन्ट आकार एवं पठनीयता",
}

PDF_STRINGS = {
    "en": {
        "title": "Legal Metrology Compliance Report",
        "subtitle": "Generated under the Legal Metrology (Packaged Commodities) Rules, 2011",
        "product_file": "Product/file",
        "scan_time": "Scan date/time",
        "score": "Compliance score",
        "location": "Location",
        "photo_evidence": "Photographic evidence",
        "found_heading": "Found declarations",
        "col_declaration": "Declaration",
        "col_value": "Extracted value",
        "col_legal_ref": "Legal reference",
        "none_found": "None found.",
        "missing_heading": "Missing declarations (violations)",
        "col_legal_ref_notes": "Legal reference / notes",
        "no_violations": "No violations detected among checked declarations.",
        "penalty_note": "Non-compliance is punishable under Section 36(1) of the Legal Metrology Act, 2009.",
        "font_disclaimer": (
            "Note on font/legibility: AI-assessed relative judgment, not a precise millimeter measurement. "
            "Borderline cases should be physically verified by an inspector."
        ),
        "footer_disclaimer": (
            "This report was auto-generated by an AI-assisted, rule-based compliance checking system and "
            "should be verified by an authorized officer before enforcement action."
        ),
        "note_prefix": "Note",
    },
    "hi": {
        "title": "विधिक माप विज्ञान अनुपालन रिपोर्ट",
        "subtitle": "विधिक माप विज्ञान (पैकेज्ड वस्तु) नियम, 2011 के अंतर्गत तैयार की गई",
        "product_file": "उत्पाद/फ़ाइल",
        "scan_time": "स्कैन दिनांक/समय",
        "score": "अनुपालन स्कोर",
        "location": "स्थान",
        "photo_evidence": "फोटोग्राफिक साक्ष्य",
        "found_heading": "पाई गई घोषणाएं",
        "col_declaration": "घोषणा",
        "col_value": "प्राप्त मान",
        "col_legal_ref": "कानूनी संदर्भ",
        "none_found": "कोई घोषणा नहीं मिली।",
        "missing_heading": "अनुपस्थित घोषणाएं (उल्लंघन)",
        "col_legal_ref_notes": "कानूनी संदर्भ / टिप्पणी",
        "no_violations": "जांची गई घोषणाओं में कोई उल्लंघन नहीं पाया गया।",
        "penalty_note": "गैर-अनुपालन विधिक माप विज्ञान अधिनियम, 2009 की धारा 36(1) के अंतर्गत दंडनीय है।",
        "font_disclaimer": (
            "फ़ॉन्ट/पठनीयता संबंधी टिप्पणी: यह AI द्वारा किया गया सापेक्ष आकलन है, सटीक मिलीमीटर माप नहीं। "
            "सीमारेखा मामलों की भौतिक रूप से किसी निरीक्षक द्वारा पुष्टि की जानी चाहिए।"
        ),
        "footer_disclaimer": (
            "यह रिपोर्ट एक AI-सहायता प्राप्त, नियम-आधारित अनुपालन जांच प्रणाली द्वारा स्वतः तैयार की गई है और "
            "प्रवर्तन कार्रवाई से पहले किसी अधिकृत अधिकारी द्वारा सत्यापित की जानी चाहिए।"
        ),
        "note_prefix": "टिप्पणी",
    },
}


def get_field_label(field, field_labels_en, lang):
    """Return the field's label in the requested language, falling back to English."""
    if lang == "hi" and field in FIELD_LABELS_HI:
        return FIELD_LABELS_HI[field]
    return field_labels_en.get(field, field)
